{
 "title": "PHP Slow Log Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Slow Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(php_fpm_slow_log_count_total[1m]))"
    }
   ]
  },
  {
   "title": "Slow Logs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time(php_fpm_slow_log_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Script Filename Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Top Script Filenames by Slow Logs",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(script_filename) (count_over_time(php_fpm_slow_log_count_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Logs Over Time by Script Filename",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by(script_filename) (count_over_time(php_fpm_slow_log_count_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Log Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Slow Log Entries",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"php-fpm\"} |= `\"topic\":\"php-fpm.slow\"`"
    }
   ]
  }
 ]
}