# Ref. https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml
service:
  flush: 1
  log_level: info
  parsers_file: /fluent-bit/etc/parsers.yaml

pipeline:
  # Ref. https://docs.fluentbit.io/manual/data-pipeline/inputs
  inputs:
    # Ref. https://docs.fluentbit.io/manual/data-pipeline/inputs/tail
    - name: tail
      path: /var/log/php-fpm/slow.log
      tag: php.slow
      # Ref. https://docs.fluentbit.io/manual/data-pipeline/inputs/tail#multiline-support
      multiline.parser: php_slow

      # Ref. https://docs.fluentbit.io/manual/data-pipeline/processors
      processors:
        logs:
          # https://docs.fluentbit.io/manual/data-pipeline/processors/content-modifier
          - name: content_modifier
            context: attributes
            action: upsert
            key: topic
            value: php-fpm.slow

          # Ref. https://docs.fluentbit.io/manual/data-pipeline/filters/modify
          - name: modify
            Rename: log raw_log

          # Ref. https://docs.fluentbit.io/manual/data-pipeline/filters/parser
          - name: parser
            parser: php_slow_fields
            key_name: raw_log
            preserve_key: on

          - name: modify
            Add: severity warning

          # Ref. https://docs.fluentbit.io/manual/data-pipeline/filters/lua
          - name: lua
            script: filters.lua
            call: append_backtrace

  # Ref. https://docs.fluentbit.io/manual/data-pipeline/outputs
  outputs:
    # Ref. https://docs.fluentbit.io/manual/data-pipeline/outputs/opentelemetry
    - name: opentelemetry
      match: '*'
      host: grafana-otel-lgtm
      port: 4318
      logs_uri: /v1/logs
      log_response_payload: true
      processors:
        logs:
          # Ref. https://docs.fluentbit.io/manual/data-pipeline/processors/opentelemetry-envelope
          - name: opentelemetry_envelope
          - name: content_modifier
            context: otel_resource_attributes
            action: upsert
            key: service.name
            value: php-fpm